### ISSUE TITLE
Content type of github entries

### ISSUE THREAD

**Issue by haesleinhuepf** [NFDI4BIOIMAGE/training#299]
There is a file "resources/nfdi4bioimage.yml" (do NOT modify this file) which contains data like this but much longer:

```
resources:
- authors:
  - Elisabeth Kugler
  name: 'Sharing Your Poster on Figshare: A Community Guide to How-To and Why'
  tags:
  - Sharing
  - Research Data Management
  type:
  - Blog
  url: https://focalplane.biologists.com/2023/07/26/sharing-your-poster-on-figshare/
- authors:
  - Marcelo Zoccoler
  license: CC-BY-4.0
  name: Running Deep-Learning Scripts in the BiA-PoL Omero Server
  tags:
  - Python
  - Artificial Intelligence
  - Bioimage Analysis
  type:
  - Blog
  url: https://biapol.github.io/blog/marcelo_zoccoler/omero_scripts/readme.html
- authors:
  - Robert Haase
  license: CC-BY-4.0
  name: Browsing the Open Microscopy Image Data Resource with Python
  tags:
  - Omero
  - Python
  type:
  - Blog
  url: https://biapol.github.io/blog/robert_haase/browsing_idr/readme.html
```

Write a notebook that loads this yml file, identifies all resources with "github.com" in the url and prints out the list of unique "type" values of these resources.

git-bob try to do this
