### ISSUE TITLE
Wrong types

### ISSUE THREAD

**Issue by haesleinhuepf** [NFDI4BIOIMAGE/training#305]
Some entries in our yaml file have type "Python" or "Big Data". We should update those and make our list of different types as short as possible. As a first step, we can adapt the notebook https://github.com/NFDI4BIOIMAGE/training/blob/main/notebooks/tag_statistics.ipynb so that it also shows "type" statistics instead of just "tag" statistics. We would then have an overview of existing types and can decide which should stay and which not. The new notebook should be called "type_statistics.ipynb".

git-bob try to do this

**Comment by haesleinhuepf** [comment]
I had to rewrite the notebook linked above. 

I propose to update all those types:
* Videos -> Video
* Publiction -> publication
* Slide -> Slides
* Online Tutorial -> Tutorial
* Online Course -> Tutorial
* Practicals -> Tutorial
* Report -> Document
* Presentation -> Slides

And I propose to remove those types:
* Big Data
* Python
* Bioimage Analysis

git-bob try to implement a new notebook that opens the "resources/nfdi4bioimage.yml" (do NOT modify this file yourself) and update it implementing the proposals above. The yml file contains data like this but much longer:

```
resources:
- authors:
  - Elisabeth Kugler
  name: 'Sharing Your Poster on Figshare: A Community Guide to How-To and Why'
  tags:
  - Sharing
  - Research Data Management
  type:
  - Blog
  url: https://focalplane.biologists.com/2023/07/26/sharing-your-poster-on-figshare/
- authors:
  - Marcelo Zoccoler
  license: CC-BY-4.0
  name: Running Deep-Learning Scripts in the BiA-PoL Omero Server
  tags:
  - Python
  - Artificial Intelligence
  - Bioimage Analysis
  type:
  - Blog
  url: https://biapol.github.io/blog/marcelo_zoccoler/omero_scripts/readme.html
- authors:
  - Robert Haase
  license: CC-BY-4.0
  name: Browsing the Open Microscopy Image Data Resource with Python
  tags:
  - Omero
  - Python
  type:
  - Blog
  url: https://biapol.github.io/blog/robert_haase/browsing_idr/readme.html
```

Again, we need python code in a jupyter notebook that updates and removes type entries in our yml file as explained above.
