### ISSUE TITLE
Count citations

### ISSUE THREAD

**Issue by haesleinhuepf** [NFDI4BIOIMAGE/training#546]
According to this discussion https://github.com/haesleinhuepf/git-bob-playground/issues/141 we could use the scholary and crossrefapi libraries to count citations of DOIs we have in our database. Reminder: DOIs are stored among urls in our resources/nfdi4bioimage.yml . Examples taken from this yml file:

```
resources:
- authors:
  - Katarzyna Biernacka
  - Katrin Cortez
  - Kerstin Helbig
  description: 'Researchers are increasingly often confronted with...'
  license: CC-BY-4.0
  name: Efficiently starting institutional research data management
  publication_date: '2019-10-15'
  tags:
  - Research Data Management
  type:
  - Document
  url:
  - https://zenodo.org/record/3490058
  - https://doi.org/10.5281/zenodo.3490058
- authors:
  - Rebecca A. Senft
  - Barbara Diaz-Rohrer
  - Pina Colarusso
  - Lucy Swift
  - Nasim Jamali
  - Helena Jambor
  - Thomas Pengo
  - Craig Brideau
  - Paula Montero Llopis
  - Virginie Uhlmann
  - Jason Kirk
  - Kevin Andrew Gonzales
  - Peter Bankhead
  - Edward L. Evans III
  - Kevin W. Eliceiri
  - Beth A. Cimini
  license: BSD-3-CLAUSE
  name: "A biologist\u2019s guide to planning and performing quantitative bioimaging\
    \ experiments"
  type:
  - Collection
  - Publication
  url: https://doi.org/10.1371/journal.pbio.3002167
```

I would like to write a new Python script similar to scripts/auto-add-github-statistics.py and scripts/auto-add-download-statistics.py . The new script goes through all entries in our yml file. For those that have a DOI link among their urls, I'd like to collect the number of citations and store them in a new "doi_statistics/20241202.csv" where the filename is the current date when the script is executed.

git-bob think about how to do this.

Hint: Do NOT modify the resources/nfdi4bioimage.yml or doi_statistics/20241202.csv directly. Write code that reads the yml file and writes the csv file.
